### ISSUE TITLE
Unable to Drive or Unlock Car After Pairing with Car

### ISSUE THREAD

**Issue by ACPark** [pccr10001/TeslaWearKey#4] opened 2022-03-12 00:10 UTC
Hi,

I've installed the apk per the instructions successfully, and paired the new key with the car. It did take some time for the car to see the key when placed on the console.

Install command:
adb install tesla_key.apk
Performing Streamed Install
Success

I renamed the apk tesla_key.apk before install. Not sure if this matters.

Post new key creation in the car the car is unable to see the watch key. It does not become bold in the key list as a card does when present.

With the car locked the car also does not see the watch key when presented to the pillar.

Using Galaxy Watch 4 (non-LTE)  Y2VX Model SM-R870
Software One UI Watch version 4.0
Software version R870XXU1EVB4 SM-R870NZSAXAC

Verified NFC is on
Verified the watch app is able enabled for NFC
Opening the app indicates the key card is ready to use.

Car: Tesla Model 3 2018 Performance

Thanks for taking a look if you are able.

**Comment by LexNastin** [comment] 2022-03-14 19:37
Same problem here, only pairs, no unlock or drive though. Rocking a TW3P here.

**Comment by pccr10001** [comment] 2022-05-05 04:00
I tested my galaxy watch 4 and galaxy watch 4 classic and it works both, but i sometimes can't unlock my car because WearOS doesn't forward NFC request to the app.
I used Proxmark 3 to capture APDUs between the car and the watch, I don't know what thing causes the issue.
Hope some guy can improve this.

**Comment by LexNastin** [comment] 2022-05-05 06:59
I don't know what the issue is, but you could ask the creator of DRIVE for Tesla because he used a fork of this app in his own, and managed to get it working.

**Comment by LexNastin** [comment] 2022-05-05 07:02
Here's his email, don't know any other contact 😅. drive@klokkprojects.no

**Comment by Bomfunk** [comment] 2022-12-14 16:25
It worked for me perfectly at first, but then I decided to test uninstalling the app and installing it again. Now my issue is exactly as described - able to pair, but unable to use the watch key in any way. What could have changed between the installations?

**Comment by stevedurbinwales** [comment] 2022-12-14 16:32
I also went over to Drive for Tesla as this project doesn't seem to be maintained and I don't have time to take it on. D4T works well, but is a cost option.

@Bomfunk 

> It worked for me perfectly at first, but then I decided to test uninstalling the app and installing it again. Now my issue is exactly as described - able to pair, but unable to use the watch key in any way. What could have changed between the installations?

I'd try deleting the watch keys from the car, two-button reboot car, then re-pair. I've had problems with the car (pairing other devices) where this worked, so it's worth a try here.

**Comment by Bomfunk** [comment] 2022-12-15 19:47
@stevedurbinwales Thanks for the suggestion.
Unfortunately, it did not work. I tried that, and many other things, like resetting the app's data through adb, looking for leftover files that might have to do something with it (unsuccessfully), reinstalling again and rebooting the watch many times, as well as the car a couple of times.
This issue really baffles me as I don't understand what could have changed between the installations - how did it work when I first installed the app and how doesn't it now? That's just so weird.

I know there's a cost option, I can always choose it if I end up needing to do so. I was just hoping that I could get an open-source/free solution. Especially considering that it proved to work before my little reinstalling experiment.

**Comment by pccr10001** [comment] 2022-12-16 00:36
I also don't know why reinstalling will cause this issue, I think AID failed to register in Android system, but I don't know why, if I reset my watch to factory default then install, it's worked, but remove it and reinstall again, it's not worked, I am confused too.

**Comment by j-marz** [comment] 2022-12-29 02:53
I was able to register key, but not able to unlock or drive car with galaxy watch 4 (non-LTE).
Using `adb logcat *:V` I noticed the following error when trying to unlock car. Hopefully helps debug this issue.
```
12-29 13:41:52.182   478   478 I keystore: !@ Start - USRPKEY_tesla_nak from uid 10106 for uid 10106
12-29 13:41:52.186   314   314 W keymaster_tee: [WRN]begin req PARAMS: A1 P4 

12-29 13:41:52.262 31325 31325 W System.err: java.lang.IllegalArgumentException: Scalar is not in the interval [1, n - 1]
12-29 13:41:52.263 31325 31325 W System.err: 	at org.bouncycastle.crypto.params.ECDomainParameters.validatePrivateScalar(Unknown Source:25)
12-29 13:41:52.263 31325 31325 W System.err: 	at org.bouncycastle.crypto.params.ECPrivateKeyParameters.<init>(Unknown Source:4)
12-29 13:41:52.263 31325 31325 W System.err: 	at org.bouncycastle.jcajce.provider.asymmetric.util.ECUtil.generatePrivateKeyParameter(Unknown Source:72)
12-29 13:41:52.263 31325 31325 W System.err: 	at org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi.initFromKey(Unknown Source:301)
12-29 13:41:52.264 31325 31325 W System.err: 	at org.bouncycastle.jcajce.provider.asymmetric.ec.KeyAgreementSpi.engineInit(Unknown Source:1)
12-29 13:41:52.264 31325 31325 W System.err: 	at javax.crypto.KeyAgreement.init(KeyAgreement.java:498)
12-29 13:41:52.264 31325 31325 W System.err: 	at javax.crypto.KeyAgreement.init(KeyAgreement.java:470)
12-29 13:41:52.264 31325 31325 W System.err: 	at li.power.app.wearos.teslanak.nfc.TeslaNAKService.doECDH(TeslaNAKService.java:192)
12-29 13:41:52.264 31325 31325 W System.err: 	at li.power.app.wearos.teslanak.nfc.TeslaNAKService.getEncryptKey(TeslaNAKService.java:201)
12-29 13:41:52.264 31325 31325 W System.err: 	at li.power.app.wearos.teslanak.nfc.TeslaNAKService.doAuthenticate(TeslaNAKService.java:212)
12-29 13:41:52.264 31325 31325 W System.err: 	at li.power.app.wearos.teslanak.nfc.TeslaNAKService.processAuthenticate(TeslaNAKService.java:179)
12-29 13:41:52.264 31325 31325 W System.err: 	at li.power.app.wearos.teslanak.nfc.TeslaNAKService.process(TeslaNAKService.java:105)
12-29 13:41:52.264 31325 31325 W System.err: 	at li.power.app.wearos.teslanak.nfc.TeslaNAKService.processCommandApdu(TeslaNAKService.java:84)
12-29 13:41:52.265 31325 31325 W System.err: 	at android.nfc.cardemulation.HostApduService$MsgHandler.handleMessage(HostApduService.java:263)
12-29 13:41:52.265 31325 31325 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-29 13:41:52.265 31325 31325 W System.err: 	at android.os.Looper.loop(Looper.java:246)
12-29 13:41:52.265 31325 31325 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7690)
12-29 13:41:52.265 31325 31325 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
12-29 13:41:52.265 31325 31325 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
12-29 13:41:52.265 31325 31325 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
12-29 13:41:52.266 31325 31325 W System.err: java.lang.IllegalArgumentException: Missing argument
12-29 13:41:52.266 31325 31325 W System.err: 	at javax.crypto.spec.SecretKeySpec.<init>(SecretKeySpec.java:93)
12-29 13:41:52.266 31325 31325 W System.err: 	at li.power.app.wearos.teslanak.nfc.TeslaNAKService.doAuthenticate(TeslaNAKService.java:212)
12-29 13:41:52.266 31325 31325 W System.err: 	at li.power.app.wearos.teslanak.nfc.TeslaNAKService.processAuthenticate(TeslaNAKService.java:179)
12-29 13:41:52.266 31325 31325 W System.err: 	at li.power.app.wearos.teslanak.nfc.TeslaNAKService.process(TeslaNAKService.java:105)
12-29 13:41:52.266 31325 31325 W System.err: 	at li.power.app.wearos.teslanak.nfc.TeslaNAKService.processCommandApdu(TeslaNAKService.java:84)
12-29 13:41:52.266 31325 31325 W System.err: 	at android.nfc.cardemulation.HostApduService$MsgHandler.handleMessage(HostApduService.java:263)
12-29 13:41:52.266 31325 31325 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-29 13:41:52.267 31325 31325 W System.err: 	at android.os.Looper.loop(Looper.java:246)
12-29 13:41:52.267 31325 31325 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7690)
12-29 13:41:52.267 31325 31325 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
12-29 13:41:52.267 31325 31325 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
12-29 13:41:52.267 31325 31325 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

12-29 13:41:52.786  1476  1769 E libnfc_nci: [ERROR:ce_t4t.cc(413)] Wrong length in ce_t4t_process_select_app_cmd
```

**Comment by Alexander-Thor** [comment] 2023-08-28 16:57
Same issue on two different Galaxy Watch 5 Pro with a Tesla Model Y. 

No problem to set it up. The car recognizes both watches straight away when adding them as keys. 

Sometimes it works great. The car unlocks / locks directly. I can park the car, lock it, get back after an hour and it unlocks directly. No problems what so ever. It's epic. 

But most of the time it's like I have close to zero signal between the clock / car. If I hold the watch still for 2 - 3 minutes the car suddenly unlocks. To lock it again I have to keep pressing the clock for a few minutes against the glass on the NFC spot. 

Then once in a while it just starts working flawlessly for half a day. 

With that said - Thank you for one of the absolute best apps on my watch. It has saved me so many times when my phone battery has gone depleted.

**Comment by nzjjay** [comment] 2024-02-09 10:58
I gave it a go on a GW6 with Tesla Model Y - no luck at all. Pairs fine, but dead afterwards.

**Comment by pccr10001** [comment] 2024-02-09 13:51
I got my new Galaxy watch 6 now and I will refector it.
PRs are also welcome.

**Comment by pccr10001** [comment] 2024-02-12 07:41
Hi guys,

I uploaded new version and tested with my Model Y, kindly check with new
version.

**Comment by nzjjay** [comment] 2024-02-12 09:34
@pccr10001 , I tested release 2 on a GW6 with Model Y, can confirm works as intended, tested door lock, unlock and drive, all functional.

**Comment by nzjjay** [comment] 2024-02-14 09:11
I have also now tested this on a 2022 Model 3 RWD (New Zealand), and fully functional (Door lock, unlock, and drive all function).

**Comment by pccr10001** [comment] 2024-02-14 09:18
@j-marz Would you please test new release again?

**Comment by j-marz** [comment] 2024-02-14 09:52
> @j-marz Would you please test new release again?

Hi @pccr10001 , thanks for the new release. Unfortunately, v1.2 is not working for me. My galaxy watch4 is not recognized by my 2022 model 3. Here's what i did:
1. Uninstall previous version of your app
2. Remove previous watch registration on car
3. Install v1.2 on watch via ADB
4. Try to register - not detected
5. Reboot watch and retry - not detected
6. Toggle NFC settings on watch - not detected
7. Reboot car - not detected
8. Confirm NFC in car is working by using existing card

Let me know if there's anything else you'd like me to capture/do? :pray:

**Comment by pccr10001** [comment] 2024-02-14 11:23
Hi @j-marz,

Please try following steps:
* Open app and check it shows "ready to use"
* Put watch to the NFC sensing zone of your phone, and check your phone detects the watch
* Try to register your watch to vehicle

If it still doesn't work, Please try:
* Install this app https://play.google.com/store/apps/details?id=com.jmarroyo.apdusendercontactless 
* Copy `00A404000FF465736C614C6F6769633030325801` to clipboard
* Open `APDU Sender Contactless` them put your watch to MFC sensing zone of your phone
* Check app detects your watch and it shows `CARD DETECT` or something with green icon on the top left
* If app crashes just restart it
* Click `Paste` in app and click `Send`
* Check logs on the bottom, it should be `ICC - 90 00` in the end

**Comment by jangamastah** [comment] 2024-02-15 06:50
Watch 4 Classic  (non-LTE) is also not working for me with 1.2

I initially had 1.1 and it paired with the car no problem, but lock/unlock/start would not work

Uninstalled and upgraded to 1.2, but now pairing with Tesla does not work. 
Factory wiped Watch and reinstalled 1.2, but still doesn't pair. 

I have made sure NFC setting is on and app opened on screen.
What I've noticed is that when the app is open, phone does not recognize NFC when I tap my watch against it. 
Phone recognized NFC (health app) when app is closed. Hopefully this helps somewhat. I can't download APDU Sender Contactless cause my phone doesn't support it.

**Comment by pccr10001** [comment] 2024-02-15 16:40
Hi @jangamastah 
Try installing Google Pay and set default NFC payment method to Google Pay in NFC setting.

APDU Sender Contactless is an open-source application, I will build it with new SDK version and upload here to let you guys to test.

**Comment by jangamastah** [comment] 2024-02-15 23:12
@pccr10001 

I  have installed Google Pay and set it as default payment. Nothing happens when tapping it to Tesla Card reader area. It's as if the watch is not shooting NFC even with the TeslaWear app open.

**Comment by pccr10001** [comment] 2024-02-17 04:48
Hi guys, 
I built the `APDU Sender Contactless` on https://github.com/pccr10001/ApduSenderContactLess/releases.
Kindly download and install it to help me to test the SELECT command is working.

Step:
* Install  `APDU Sender Contactless` from repo's release page.
* Tap your watch to phone's NFC sensing zone.
* Check watch is detected
* Select `SELECT TESLA NAK` from `Built-In APDUs.`
* Click `Send` and check response is `ICC - 90 00`

BTW, I tested with following devices and confirmed they are working with v1.2 
* Galaxy Watch 4 Classic LTE with Android 11 Wear OS 3.5 OneUI 4.5
* Galaxy Watch 4 LTE with Android 11 Wear OS 3.2 OneUI 4.0
* Galaxy Watch 6 LTE with Android 13 Wear OS 4.0 OneUI 5.0

**Comment by j-marz** [comment] 2024-02-17 06:37
@pccr10001 thanks for the updated tool. I'm receiving `ICC - 90 00` response.
I've tried disabling other NFC apps on watch, but not change. My model 3 doesn't detect the watch while `add key` menu is open. Really weird issue.

**Comment by pccr10001** [comment] 2024-02-17 08:24
Hi @j-marz,
I built a mobile `TeslaWearKey` app for Android phone to log traffic, please rename it from `.zip` to `.apk`, and install it on your phone.
Please use your phone as key card and register to vehicle, then click the `Mail` button to get the log and share to here.
I will analysis it and try to find the solution.

[teslanak_mobile.zip](https://github.com/pccr10001/TeslaWearKey/files/14318177/teslanak_mobile.zip)

**Comment by Lineflyer** [comment] 2024-02-17 12:19
Hi all,

I had problems in the past using this tool on my 2022 Model 3 using Galaxy Watch 6. I could add the watch as key but failed to unlock for doors or drive.

I did now install the 1.2 version from the git release. I started the app on the watch and tapped to my phone, which repors "NFC tag detected application/vnd.shealth.le.oob"
Seemingly the Samsung Health app blocks the NFC interface....could that be the problem?
Will still try tonight if I can register and unlock with the watch (car is not nearby right now).

**Comment by pccr10001** [comment] 2024-02-17 14:50
Hi @Lineflyer,

Could you try the mobile app 
in this comment?
 https://github.com/pccr10001/TeslaWearKey/issues/4#issuecomment-1949898286

**Comment by pccr10001** [comment] 2024-02-17 19:11
Hi guys,

I found a mistake on EC key generation that causes registration will be success but unlock fails and the issue has been fixed.
Please check with the new release v1.3.
Please wipe the app's data or remove it and reinstall it

**Comment by Lineflyer** [comment] 2024-02-17 21:43
@pccr10001 
Either I made a mistake while installing 1.3 or there is something strange:
It installs a "APDU Sender Contactless" app/icon which does nothing once I tap it in the launcher.

**Comment by j-marz** [comment] 2024-02-17 21:48
Same here. v1.3 release has wrong app asset uploaded.

**Comment by pccr10001** [comment] 2024-02-18 02:41
I am sorry for that lol, new apk is uploaded to release v1.3

**Comment by Lineflyer** [comment] 2024-02-21 21:58
@pccr10001 Will test as time permits and provide feedback.

**Comment by pccr10001** [comment] 2024-02-29 15:59
Hi guys, any issues found?
Or I can close this issue.
BTW Google Play link is updated, welcome to download it from Google Play.

**Comment by Lineflyer** [comment] 2024-03-01 20:08
I am sorry for the late feedback:
I installed it directly from Google Play (yesterday...so probably not yet V1.3.5 you just released).

It doesn't work on my Galaxy Watch 6:
- I can start the app and see the "keep active..."
- I started adding a new key in the car and tapped the watch....the car does not react to it

**Comment by pccr10001** [comment] 2024-03-02 00:37
Hi @Lineflyer 
Please update it, Google Play makes crypto library broken.

**Comment by Lineflyer** [comment] 2024-03-02 10:24
Will update and try again.

Edit: Will uninstall and install 1.3.5 afterwards

**Comment by pccr10001** [comment] 2024-03-02 11:09
Hi @Lineflyer 
Please install from release page, Google is still reviewing v1.3.6, you can direct install from release page, `15.apk` is signed by Google, so it can be install directly.
v1.3.5 is still buggy on some watches.

**Comment by j-marz** [comment] 2024-03-03 06:46
Thanks for persisting with updates @pccr10001 . v1.3.6 (15.apk) is now working for me. :tada: 

On first attempt it was the same behavior (watch not detected), but this time I deleted my physical key card through car menu and noticed it wasn't removed from the list... Tried removing physical key card again, but still in the list. Tried adding galaxy watch4 and it was detected! Used the same physical key card to authorise the watch and confirmed the watch is working to unlock/lock car.

Weird that the physical key was never removed from the list of keys on my model 3. Attempting to remove it seems to cleared up the cars inability to detect my galaxy watch4 though, so i'm happy :smile:

**Comment by pccr10001** [comment] 2024-03-03 14:13
Hi @j-marz 
Glad to hear about this.
Google Play is still reviewing my submission, it takes a long long time.

**Comment by Lineflyer** [comment] 2024-03-03 21:39
> Hi @Lineflyer Please install from release page, Google is still reviewing v1.3.6, you can direct install from release page, `15.apk` is signed by Google, so it can be install directly. v1.3.5 is still buggy on some watches.

Only read that, however v1.3.5 worked on my Galaxy Watch 6 to pair, unlock and drive my Tesla Model 3 LongRange 2022. 👍🏼 

Will upgrade to 1.3.6 as soon as available.

**Comment by pccr10001** [comment] 2024-03-13 08:03
I closed this issue, if you guys have any question, just reopen it

**Closed as completed by pccr10001** 2024-03-13 08:03 UTC

**Comment by Lineflyer** [comment] 2024-03-13 19:54
@pccr10001 
Still, some late feedback with V1.3.7:
Model 3 LR 2022, no problem to pair and use for unlock and drive. Thanks!
